### ISSUE TITLE
retorno da transação

### ISSUE THREAD

**Issue by DaywisonFerreira** [brunopazz/GetnetSDK#12]
Segui o seu exemplo e fiz uma transação com cartão no sandbox e me retornou AUTHORIZED .
Queria saber se essse status quer dizer que o pagamento foi PAGO ?

**Comment by brunopazz** [comment]
Sim, quer dizer que foi aprovado.

Atenciosamente,

Bruno Paz
brunopaz@gmail.com
https://www.linkedin.com/in/brunopazz
