### ISSUE TITLE
Alteração de Status de Pagamento.

### ISSUE THREAD

**Issue by DaywisonFerreira** [brunopazz/GetnetSDK#13]
Olá Bruno, desculpa o incomodo é que estou implementando a API GETNET aqui no sistema de ecommerce da empresa, gostaria de saber se é possível a alteração de "Status" de um pagamento direto da API, e se após essa alteração o GETNET envia algum POST para o sistema dizendo dessa alteração de "Status", se eu não me engano o PAGSEGURO tem isso, mas não sei se o GETNET tem, pode me dizer ?

**Comment by Pr3d4dor** [comment]
Você precisa configurar uma rota públiba para receber os callbacks enviados pelo GETNET, conforme a documentação na parte de callbacks:

https://developers.getnet.com.br/faq

**Comment by brunopazz** [comment]
Você pode usar o que o Gianluca comentou. Complementando, um status de cartão de crédito não fica alterando depois da confirmação de pagamento. Já o boleto pode sofrer depois de emitido.

Atenciosamente,

Bruno Paz
brunopaz@gmail.com
https://www.linkedin.com/in/brunopazz
