### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by DaywisonFerreira** [brunopazz/GetnetSDK#14]
Olá Bruno, uma última dúvida, os dados abaixo:
seller_id
client_id
client_secret
utilizados no ambiente de homologação, são os mesmos utilizados em ambiente de produção?

**Comment by brunopazz** [comment]
Se não estou enganado, o de produção é enviado pelo gerente da conta da Getnet ( Santander) no ato da contratação.

Atenciosamente,

Bruno Paz
brunopaz@gmail.com
https://www.linkedin.com/in/brunopazz
