### ISSUE TITLE
Geração de Boleto

### ISSUE THREAD

**Issue by DaywisonFerreira** [brunopazz/GetnetSDK#15]
Boa tarde Bruno, eu estou implementando o pagamento via Boleto utilizando o Getnet o que acontece é que quando estou utilizando as credenciais do ambiente SANDBOX consigo gerar o boleto normalmente porém quando uso as credenciais do ambiente de HOMOLOGAÇÃO o sistema me retorna esse erro abaixo, pode me ajudar ?  

Fatal error: Call to undefined method Getnet\API\BaseResponse::getBoletoHtml()

**Comment by billbarsch** [comment]
olá @DaywisonFerreira 
o que acontece é que está dando erro na geração do seu boleto
quando o boleto não é gerado, a resposta não tem essa informação do html dele
dai esse metodo fica indefinido
ou seja, se tivesse dado sucesso teria valor sim nesse metodo.
uma coisa interessante que notei é que quando dá erro a classe retornada é a BaseResponse
mas quando dá sucesso a classe retornada é outra: BoletoResponse
ou seja, o metodo GetBoletoHtml não existe dentro da classe BaseResponse, ele só existe dentro da clase BoletoResponse.
Isso quebrou minha cabeça mas descobri que se você verificar antes de acessar o método, qual tipo de classe foi retornada você acaba fazendo um código mais confiavel assim:

if($response instanceof \Getnet\API\BoletoRespose)
  $htmlDoBoleto = $response->getBoletoHtml();
