### ISSUE TITLE
Erro no antifraude

### ISSUE THREAD

**Issue by DaywisonFerreira** [brunopazz/GetnetSDK#16]
Olá Bruno, estou usando sua classe do GetNet e no ambiente de SANDBOX ou HOMOLOGAÇÃO eu consigo efetuar as compras normalmente, mas quando utilizado as credenciais de PRODUÇÃO a API me retorna no erro abaixo, pode me ajudar? 

{
    "message": "DENY",
    "name": "CreditServiceError",
    "status_code": 402,
    "details": [{
        "antifraud": {
            "code": "DENY",
            "description": "Transacao Negada!",
            "transaction_token": "AhjzbwSTLYST5sxfUEflMgJRe6e75OftCfpHNrw6SZejFdbkoB8AxkaY",
            "transaction_id": "5562023199186604804069",
            "transaction_reference_code": "f4320f30-6765-11e9-9917-b189916f1f64",
            "transaction_datetime": "2019-04-25T14:25:21.665Z"
        },
        "brand": "mastercard",
        "payment_id": "b283d82d-11b6-4069-89af-7f82edafe07e"
    }]
}

**Comment by Pr3d4dor** [comment]
Você implementou a parte do antifraude?

Documentação: https://developers.getnet.com.br/api#section/Antifraude

**Comment by DaywisonFerreira** [comment]
Eu inclui o script do antifraude no meu head :

`<script type="text/javascript" src="https://h.online-metrix.net/fp/tags.js?org_id=k8vif92e&session_id=103"></script>`

E inclui o input hidden abaixo no meu formulário de pagamento.

`<input type="hidden" name="deviceFingerprintID" value="103" />`

Quando faço a requisição da API do GetNet utilizando as credenciais de produção, me retorna o erro que informei anteriomente.

**Comment by Pr3d4dor** [comment]
No PHP na rota de recebimento do formulário você está enviando/settando o valor vindo do campo `deviceFingerprintID` para enviar para o Getnet?

Além disso é necessário enviar o endereço IP do cliente no momento que o mesmo estiver tentando fazer a compra.

Exemplo:
```php
$deviceFingerPrint = 'alguma_coisa' // Receber esse valor vindo do formulário.
$ip = 'bla-bla' // Receber o endereço ip do cliente tentando fazer a compra.

// FingerPrint - Antifraude
// Setar esses valores na tentativa de transação
$transaction->Device($deviceFingerPrint)->setIpAddress($ip);
```

**Comment by Pr3d4dor** [comment]
Também recomento você usar uma forma melhor de gerar o `session_id` dos clientes no momento da compra, pois esse valor deve ser único e ter validade de 48 horas conforme a documentação.

**Comment by gustavo2019x** [comment]
Estou com esse mesmo problema do antifraude em um aplicativo (mesmo erro da imagem) e não passei os valores do "fingerPrint", provavelmente é isso. Mas na API fala se eu não tiver endereço de entrega, atributo "shippings" eu preciso usar os mesmos dados do atributo "billing_address". Porém o aplicativo em questão não exige nenhuma informação referente ao endereço do cliente, é possível resolver esse problema sem o endereço?

**Comment by Pr3d4dor** [comment]
Creio que não porque o endereço também é usado na hora de autorizar o pagamento pelo Santander GetNet.

**Comment by gustavo2019x** [comment]
O problema do antifraude foi corrigido! Valeu. Só uma dúvida, vocês tem bastante o retorno de erro 402, alguns como transação não aprovada solicite ao cliente contatar Emissor (payments-116). E também o payments-002, muitos clientes estão tentando comprar e retornando esses erros, será que eles estão errando algo realmente?

**Comment by Pr3d4dor** [comment]
Nós conseguimos diminuir a incidência desses erros implementando justamente essa parte do fingerprint.

**Comment by gustavo2019x** [comment]
O estranho que a cada 3 tentativas de pagamento, 1 falha. E tudo foi implementado... :/

**Comment by Pr3d4dor** [comment]
Talvez você possa pedir um feedback ao Santander GetNet quanto esses pagamentos para ver se eles estão realmente caindo no anti-fraude. Se estiverem caindo recomendo verificar se a lógica do fingerprint está funcionando.

**Comment by gustavo2019x** [comment]
Foi solucionado essa parte, obrigado! Uma dúvida sobre segurança, vocês fazem requisições de pagamento/salvar cartão direto do cliente p/ getnet, ou a requisição passa antes em um webservice pra depois ir para getnet?

**Comment by Pr3d4dor** [comment]
A requisição antes passa pelo API no nosso backend e na API é disparado a requisição ao GetNet.

**Comment by gabrielhrp31** [comment]
como voces resolveram? estou usando um spa mas nn faço ideia de como implementar o antifraude! Se puderem me ajudar ficaria grato falta só isso pra eu terminar o trampo!

**Comment by FilipeOliveiraAlvares** [comment]
Eu peguei um  sistema para corrigir  o qual funcionava ano passado (2019)  sem  ter implementado a  parte do antfraud ($transaction->device("device_id")->setIpAddress("127.0.0.1");)
Testei e dava o mesmo erro mencionando acima.

-- eu adicionei a parte do antfraug e continua o mesmo erro, idêntico .  

 
   "payment_id":"d340563c-aa9e-427b-89c5-9caf802ff11c",
   "seller_id":null,
   "amount":null,
   "currency":null,
   "order_id":null,
   "status":null,
   "received_at":null,
   "error_message":null,
   "description":"Transacao negada.afpd!",
   "description_detail":null,
   "status_code":"481",
   "responseJSON":"{\n    \"message\": \"DENY\",\n    \"name\": \"CreditServiceError\",\n    \"status_code\": 402,\n    \"details\": [\n        {\n            \"antifraud\": {\n                \"code\": \"DENY\",\n                \"status_code\": \"481\",\n                \"description\": \"Transacao negada.afpd!\",\n                \"transaction_token\": \"AxjzbwSTSr+yCZT6dFcS\\\/+YCTyfaCpe72hm1gfgvDpJl6MV1uOwGgAAA0AKR\",\n                \"transaction_id\": \"6101238657866712504082\",\n                \"transaction_reference_code\": \"d340563c-aa9e-427b-89c5-9caf802ff11c\",\n                \"transaction_datetime\": \"2021-01-08T16:37:46.435Z\",\n                \"device_fingerprint\": {\n                    \"received\": false\n                },\n                \"score\": \"89\"\n            },\n            \"brand\": \"mastercard\",\n            \"payment_id\": \"d340563c-aa9e-427b-89c5-9caf802ff11c\"\n        }\n    ]\n}",
   "status_label":null
}

**Comment by FilipeOliveiraAlvares** [comment]
Consegui resolver - até então estava tentando resolver pelo Backend mas sem sucesso.

Colocando o link dava script na pagina e passando a variável por um input hidden no formulário, deu certo !

**Comment by guilhermehrcosta** [comment]
@FilipeOliveiraAlvares Como vc resolveu o erro ? Adicionou colocando para carregar o link na página ? Somente isto ?

**Comment by gustavo2019x** [comment]
Seu back end é um app em flutter? Existe esse tópico na documentação  "Capturando Device Fingerprint em aplicação/serviço Backend" : https://developers.getnet.com.br/api#section/Antifraude/Implementando-o-Device-Fingerprint

**Comment by augusto3691** [comment]
Para quem tiver tendo esse erro, em ambiente de homologação o e-mail aceito pelo antifraude é o `aceitei@getnet.com.br`
