### ISSUE TITLE
Device Fingerprint

### ISSUE THREAD

**Issue by gabrielhrp31** [brunopazz/GetnetSDK#18]
olá bruno conseguiria me dar uma ajuda em relação ao device fingerprint estou com duvidas ao gerar o mesmo e tambem como implementar essa lógica! Desde já agradeceria muito pois falta só isso pra finalizar um projeto! Eu  li na issue closed mas nn foi mt bem explicada a lógica!

**Comment by Pr3d4dor** [comment]
A documentação é essa: https://developers.getnet.com.br/api#section/Antifraude/Implementando-o-Device-Fingerprint

**Comment by gabrielhrp31** [comment]
Ok blz! Li a documentação mas nn consegui pensar em uma maneira de mudar esse codigo de 48 em 48horas

**Comment by gabrielhrp31** [comment]
eu poderia usar o csrf_token?

**Comment by Pr3d4dor** [comment]
Você está usando Laravel como API em conjunto com uma SPA?

Se sim qual framework de frontend?

**Comment by gabrielhrp31** [comment]
parece que o csrf_token vai funcionar poise ele se altera constantemente, estou usando vuejs

**Comment by Pr3d4dor** [comment]
Sim a cada requisição ele altera o token.
