### ISSUE TITLE
Setter fluente para chain de métodos

### ISSUE THREAD

**Issue by trialforce** [brunopazz/GetnetSDK#3]
Olá Bruno!

Acabei de iniciar a integração com a Getnet usando sua biblioteca no e-commerce da empresa que trabalho. 

Logo já vi que está bem estruturada e funcional.

Ainda vou mais a fundo no uso da biblioteca, mas de cara vi que você não retorna o $this nos métodos set o que evita a possibilidade do "chain" ou seja de "acorrentar" as chamadas de métodos umas na outras.

No seu exemplo:

```
$transaction = new Transaction();
$transaction->setSellerId($sellerId);
$transaction->setCurrency("BRL");
$transaction->setAmount("1000");
```

Poderia ser:
```
$transaction = new Transaction();
$transaction->setSellerId($sellerId)->setCurrency("BRL")->setAmount("1000");
```

No exemplo do seu código do setSellerId ficará conforme abaixo.

```
/**
     * @param mixed $seller_id
     */
    public function setSellerId($seller_id)
    {
        $this->seller_id = $seller_id;
        
        return $this;
    }

```

Offtopic:

Não vi exemplo de guardar o número do cartão para futuro uso pelo usuário.

Posso desenvolver e enviar para você? Ou você já tem isso pronto?

**Comment by brunopazz** [comment]
Obrigado pelo comentários, fique a vontade em fazer um PR para ajustar. Não implementei o "cofre" para armazenar na Getnet. Criei esse SDK para justamente ajudar a comunidade e receber ajuda. Qualquer ajuda é bem-vinda.

> Olá Bruno!
> 
> Acabei de iniciar a integração com a Getnet usando sua biblioteca no e-commerce da empresa que trabalho.
> 
> Logo já vi que está bem estruturada e funcional.
> 
> Ainda vou mais a fundo no uso da biblioteca, mas de cara vi que você não retorna o $this nos métodos set o que evita a possibilidade do "chain" ou seja de "acorrentar" as chamadas de métodos umas na outras.
> 
> No seu exemplo:
> 
> ```
> $transaction = new Transaction();
> $transaction->setSellerId($sellerId);
> $transaction->setCurrency("BRL");
> $transaction->setAmount("1000");
> ```
> Poderia ser:
> 
> ```
> $transaction = new Transaction();
> $transaction->setSellerId($sellerId)->setCurrency("BRL")->setAmount("1000");
> ```
> No exemplo do seu código do setSellerId ficará conforme abaixo.
> 
> ```
> /**
>      * @param mixed $seller_id
>      */
>     public function setSellerId($seller_id)
>     {
>         $this->seller_id = $seller_id;
>         
>         return $this;
>     }
> ```
> Offtopic:
> 
> Não vi exemplo de guardar o número do cartão para futuro uso pelo usuário.
> 
> Posso desenvolver e enviar para você? Ou você já tem isso pronto?

Obrigado pelo comentários, fique a vontade em fazer um PR para ajustar. Não implementei o "cofre" para armazenar na Getnet. Criei esse SDK para justamente ajudar a comunidade e receber ajuda. Qualquer ajuda é bem-vinda.
