### ISSUE TITLE
"security_code" must be a string

### ISSUE THREAD

**Issue by trialforce** [brunopazz/GetnetSDK#5]
Olá Bruno!

Ao fazer setSecurityCode(123) recebo o seguinte erro da Getnet.

**"security_code" must be a string**

Para resolver isso preciso passar o número entre aspas, mas isso é simples de resolver se no método setSecurityCode efetuarmos a conversão para string conforme o exemplo abaixo.

O mesmo caso acontece com o setExpirationMonth e setExpirationYear.

```
/**
     * @param mixed $security_code
     * @return Card
     */
    public function setSecurityCode($security_code)
    {
        $this->security_code = $security_code . "";

        return $this;
    }
```

**Comment by trialforce** [comment]
Reperei o mesmo caso com o customer_id no token e no request.

**Comment by brunopazz** [comment]
Foi ajustado.
