### ISSUE TITLE
Permitir cartão sem bandeira

### ISSUE THREAD

**Issue by trialforce** [brunopazz/GetnetSDK#6]
A documentação da getnet permite a criação de pagamentos sem informar a bandeira.

A biblioteca hoje não permite, fiz esse "hack" para funcionar.

É mais fácil para o cliente não precisar informar a bandeira.

O que você acha?

```
public function toJSON()
    {
        $vars = get_object_vars($this);

        //atualiza objeto de cartão para funcionar sem bandeira
        $card = $vars['credit']->getCard();

        $newCard = new \stdClass();

        if ($card->getBrand())
        {
            $newCard->brand = $card->getBrand();
        }

        $newCard->cardholder_name = $card->getCardholderName();
        $newCard->expiration_month = $card->getExpirationMonth();
        $newCard->expiration_year = $card->getExpirationYear();
        $newCard->number_token = $card->getNumberToken();
        $newCard->security_code = $card->getSecurityCode();

        $vars['credit']->setCard($newCard);

        return json_encode($vars, JSON_PRETTY_PRINT);
    }
```

**Comment by brunopazz** [comment]
Fiz um ajuste um pouco melhor. Caso você não set, irá funcionar também.

`
$transaction->Credit("")
    ->setAuthenticated(false)
    ->setDynamicMcc("1799")
    ->setSoftDescriptor("LOJA*TESTE*COMPRA-123")
    ->setDelayed(false)
    ->setPreAuthorization(false)
    ->setNumberInstallments("2")
    ->setSaveCardData(false)
    ->setTransactionType("FULL")
    ->Card($card)
    ->setBrand("MasterCard")
    ->setExpirationMonth("12")
    ->setExpirationYear("20")
    ->setCardholderName("Bruno Paz")
    ->setSecurityCode(123);
`
