### ISSUE TITLE
Erro ao fazer transação

### ISSUE THREAD

**Issue by jsuceir** [brunopazz/GetnetSDK#7]
Dados dos itens invalidos
P2AAA0372237|SUSPEND|DENY|0700

Passei o cartão uma vez deu certo, mas dps comecou da essa mensagem

**Comment by brunopazz** [comment]
Poderia dar mais detalhes por favor.

**Comment by jsuceir** [comment]
seguinte, passei uns cartoes para testes passou 3 vezes dps comecou da esse erro, e em todos cartoes VISA da problema
